import type { Rapper } from "../src/types/types";

function calculateAge(
  birthYear: number,
  birthMonth: number,
  birthDay: number
): number {
  const today = new Date();
  const birth = new Date(birthYear, birthMonth - 1, birthDay);
  let years: number = today.getFullYear() - birth.getFullYear();
  if (today.getMonth() + 1 <= birth.getMonth()) {
    if (today.getDate() < birthDay) {
      years--;
    }
  }
  return years;
}

const rappers: Rapper[] = [
  {
    name: "Travis Scott",
    age: calculateAge(1991, 4, 30),
    genre: ["Trap"],
    from: "Houston, Texas",
    monthly: "60M+",
    debut: 2013,
  },
  {
    name: "Future",
    age: calculateAge(1983, 11, 20),
    genre: ["Trap"],
    from: "Atlanta, Georgia",
    monthly: "55M+",
    debut: 2012,
  },
  {
    name: "Lil Wayne",
    age: calculateAge(1982, 9, 27),
    genre: ["Rap"],
    from: "New Orleans, Louisiana",
    monthly: "45M+",
    debut: 1999,
  },
  {
    name: "Lil Baby",
    age: calculateAge(1994, 12, 3),
    genre: ["Trap"],
    from: "Atlanta, Georgia",
    monthly: "30M+",
    debut: 2017,
  },
  {
    name: "Nicki Minaj",
    age: calculateAge(1982, 12, 8),
    genre: ["Rap", "Pop"],
    from: "Trinidad and Tobago",
    monthly: "45M+",
    debut: 2007,
  },
  {
    name: "Cardi B",
    age: calculateAge(1992, 10, 11),
    genre: ["Rap", "Pop"],
    from: "New York City, New York",
    monthly: "25M+",
    debut: 2015,
  },
  {
    name: "Megan Thee Stallion",
    age: calculateAge(1995, 2, 15),
    genre: ["Rap", "Pop"],
    from: "Houston, Texas",
    monthly: "25M+",
    debut: 2016,
  },
  {
    name: "Doja Cat",
    age: calculateAge(1996, 10, 21),
    genre: ["Pop", "Rap"],
    from: "Los Angeles, California",
    monthly: "50M+",
    debut: 2014,
  },
  {
    name: "Ice Spice",
    age: calculateAge(2000, 1, 1),
    genre: ["Trap"],
    from: "New York City, New York",
    monthly: "10M+",
    debut: 2021,
  },
  {
    name: "Latto",
    age: calculateAge(1998, 12, 22),
    genre: ["Trap"],
    from: "Atlanta, Georgia",
    monthly: "15M+",
    debut: 2016,
  },
  {
    name: "GloRilla",
    age: calculateAge(1999, 7, 28),
    genre: ["Trap"],
    from: "Memphis, Tennessee",
    monthly: "15M+",
    debut: 2019,
  },
  {
    name: "Doechii",
    age: calculateAge(1998, 3, 29),
    genre: ["Rap"],
    from: "Tampa, Florida",
    monthly: "45M+",
    debut: 2020,
  },
  {
    name: "Kendrick Lamar",
    age: calculateAge(1987, 6, 17),
    genre: ["Rap"],
    from: "Compton, California",
    monthly: "85M+",
    debut: 2011,
  },
  {
    name: "Drake",
    age: calculateAge(1986, 10, 24),
    genre: ["Rap", "Pop", "R&B"],
    from: "Toronto, Canada",
    monthly: "80M+",
    debut: 2009,
  },
  {
    name: "Playboi Carti",
    age: calculateAge(1996, 9, 13),
    genre: ["Trap"],
    from: "Atlanta, Georgia",
    monthly: "50M+",
    debut: 2017,
  },
  {
    name: "Youngboy NBA",
    age: calculateAge(1999, 10, 20),
    genre: ["Trap"],
    from: "Baton Rouge, Louisiana",
    monthly: "15M+",
    debut: 2015,
  },
  {
    name: "Lil Durk",
    age: calculateAge(1992, 10, 19),
    genre: ["Trap"],
    from: "Chicago, Illinois",
    monthly: "15M+",
    debut: 2010,
  },
  {
    name: "21 Savage",
    age: calculateAge(1992, 10, 22),
    genre: ["Trap"],
    from: "London, England",
    monthly: "40M+",
    debut: 2016,
  },
  {
    name: "J. Cole",
    age: calculateAge(1985, 1, 28),
    genre: ["Rap"],
    from: "Fayetteville, North Carolina",
    monthly: "35M+",
    debut: 2007,
  },
  {
    name: "Tyler, The Creator",
    age: calculateAge(1991, 3, 6),
    genre: ["Rap"],
    from: "Los Angeles, California",
    monthly: "40M+",
    debut: 2007,
  },
  {
    name: "Ken Carson",
    age: calculateAge(2000, 7, 18),
    genre: ["Trap"],
    from: "Atlanta, Georgia",
    monthly: "5M+",
    debut: 2017,
  },
  {
    name: "Central Cee",
    age: calculateAge(1998, 6, 4),
    genre: ["Trap", "Drill"],
    from: "London, England",
    monthly: "20M+",
    debut: 2015,
  },
  {
    name: "Quavo",
    age: calculateAge(1991, 4, 2),
    genre: ["Rap", "Trap"],
    from: "Lawrenceville, Georgia",
    monthly: "15M+",
    debut: 2012,
  },
  {
    name: "Lil Uzi Vert",
    age: calculateAge(1994, 7, 31),
    genre: ["Trap", "Emo Rap"],
    from: "Philadelphia, Pennsylvania",
    monthly: "25M+",
    debut: 2014,
  },
  {
    name: "A$AP Rocky",
    age: calculateAge(1988, 10, 3),
    genre: ["Rap"],
    from: "Harlem, New York City",
    monthly: "35M+",
    debut: 2011,
  },
  {
    name: "Gunna",
    age: calculateAge(1993, 6, 14),
    genre: ["Trap"],
    from: "College Park, Georgia",
    monthly: "30M+",
    debut: 2016,
  },
  {
    name: "NLE Choppa",
    age: calculateAge(2002, 11, 1),
    genre: ["Trap"],
    from: "Memphis, Tennessee",
    monthly: "15M+",
    debut: 2018,
  },
  {
    name: "Don Toliver",
    age: calculateAge(1994, 6, 12),
    genre: ["Trap", "Rap", "R&B"],
    from: "Houston, Texas",
    monthly: "35M+",
    debut: 2017,
  },
  {
    name: "Lil Tjay",
    age: calculateAge(2001, 4, 30),
    genre: ["Trap"],
    from: "The Bronx, New York",
    monthly: "10M+",
    debut: 2016,
  },
  {
    name: "Polo G",
    age: calculateAge(1999, 1, 6),
    genre: ["Rap"],
    from: "Chicago, Illinois",
    monthly: "15M+",
    debut: 2016,
  },
  {
    name: "Jack Harlow",
    age: calculateAge(1998, 3, 13),
    genre: ["Rap"],
    from: "Louisville, Kentucky",
    monthly: "25M+",
    debut: 2015,
  },
  {
    name: "Lil Yachty",
    age: calculateAge(1997, 8, 23),
    genre: ["Rap", "Trap"],
    from: "Mableton, Georgia",
    monthly: "15M+",
    debut: 2015,
  },
  {
    name: "Ski Mask the Slump God",
    age: calculateAge(1996, 4, 18),
    genre: ["Trap"],
    from: "Fort Lauderdale, Florida",
    monthly: "5M+",
    debut: 2015,
  },
  {
    name: "Denzel Curry",
    age: calculateAge(1995, 2, 1),
    genre: ["Rap", "Alternative Rap"],
    from: "Carol City, Florida",
    monthly: "5M+",
    debut: 2011,
  },
  {
    name: "Freddie Gibbs",
    age: calculateAge(1982, 6, 14),
    genre: ["Rap", "Gangsta Rap"],
    from: "Gary, Indiana",
    monthly: "3M+",
    debut: 2004,
  },
  {
    name: "Logic",
    age: calculateAge(1990, 1, 22),
    genre: ["Rap"],
    from: "Gaithersburg, Maryland",
    monthly: "5M+",
    debut: 2010,
  },
  {
    name: "Wiz Khalifa",
    age: calculateAge(1987, 9, 8),
    genre: ["Rap"],
    from: "Minot, North Dakota",
    monthly: "40M+",
    debut: 2005,
  },
  {
    name: "Mac Miller",
    age: 26,
    genre: ["Rap"],
    from: "Pittsburgh, Pennsylvania",
    monthly: "25M+",
    debut: 2007,
  },
  {
    name: "Juice WRLD",
    age: 21,
    genre: ["Rap", "Emo Rap"],
    from: "Chicago, Illinois",
    monthly: "25M+",
    debut: 2015,
  },
  {
    name: "Pop Smoke",
    age: 20,
    genre: ["Drill"],
    from: "Brooklyn, New York",
    monthly: "15M+",
    debut: 2018,
  },
  {
    name: "XXXTentacion",
    age: 20,
    genre: ["Trap", "Emo Rap"],
    from: "Plantation, Florida",
    monthly: "30M+",
    debut: 2014,
  },
  {
    name: "Post Malone",
    age: calculateAge(1995, 7, 4),
    genre: ["Rap", "Pop", "R&B"],
    from: "Syracuse, New York",
    monthly: "70M+",
    debut: 2015,
  },
  {
    name: "The Weekend",
    age: calculateAge(1990, 2, 16),
    genre: ["R&B", "Pop"],
    from: "Toronto, Canada",
    monthly: "115M+",
    debut: 2010,
  },
  {
    name: "JID",
    age: calculateAge(1990, 10, 31),
    genre: ["Rap"],
    from: "Atlanta, Georgia",
    monthly: "15M+",
    debut: 2010,
  },
  {
    name: "Lil Tecca",
    age: calculateAge(2002, 8, 26),
    genre: ["Rap"],
    from: "Queens, New York",
    monthly: "25M+",
    debut: 2017,
  },
  {
    name: "2Pac",
    age: calculateAge(1971, 6, 16),
    genre: ["Rap", "Gangsta Rap"],
    from: "East Harlem, New York",
    monthly: "25M+",
    debut: 1991,
  },
  {
    name: "The Notorious B.I.G.",
    age: calculateAge(1972, 5, 21),
    genre: ["Rap", "Gangsta Rap"],
    from: "Brooklyn, New York",
    monthly: "20M+",
    debut: 1992,
  },
  {
    name: "Nas",
    age: calculateAge(1973, 9, 14),
    genre: ["Rap", "Gangsta Rap"],
    from: "Queens, New York",
    monthly: "5M+",
    debut: 1991,
  },
  {
    name: "Jay-Z",
    age: calculateAge(1969, 12, 4),
    genre: ["Rap"],
    from: "Brooklyn, New York",
    monthly: "30M+",
    debut: 1996,
  },
  {
    name: "Eminem",
    age: calculateAge(1972, 10, 17),
    genre: ["Rap"],
    from: "Detroit, Michigan",
    monthly: "65M+",
    debut: 1996,
  },
  {
    name: "Snoop Dogg",
    age: calculateAge(1971, 10, 20),
    genre: ["Rap", "Gangsta Rap"],
    from: "Long Beach, California",
    monthly: "30M+",
    debut: 1992,
  },
  {
    name: "Dr. Dre",
    age: calculateAge(1965, 2, 18),
    genre: ["Rap", "Gangsta Rap"],
    from: "Compton, California",
    monthly: "20M+",
    debut: 1986,
  },
  {
    name: "Ice Cube",
    age: calculateAge(1969, 6, 15),
    genre: ["Rap", "Gangsta Rap"],
    from: "Los Angeles, California",
    monthly: "15M+",
    debut: 1986,
  },
  {
    name: "DMX",
    age: calculateAge(1970, 12, 18),
    genre: ["Rap", "Gangsta Rap"],
    from: "Mount Vernon, New York",
    monthly: "10M+",
    debut: 1992,
  },
  {
    name: "50 Cent",
    age: calculateAge(1975, 7, 6),
    genre: ["Rap", "Gangsta Rap"],
    from: "Queens, New York",
    monthly: "35M+",
    debut: 2000,
  },
  {
    name: "Kanye West",
    age: calculateAge(1977, 6, 8),
    genre: ["Rap"],
    from: "Chicago, Illinois",
    monthly: "60M+",
    debut: 2004,
  },
  {
    name: "The Game",
    age: calculateAge(1979, 11, 29),
    genre: ["Rap", "Gangsta Rap"],
    from: "Compton, California",
    monthly: "10M+",
    debut: 2004,
  },
  {
    name: "Rick Ross",
    age: calculateAge(1976, 1, 28),
    genre: ["Rap"],
    from: "Cartersville, Georgia",
    monthly: "10M+",
    debut: 2006,
  },
  {
    name: "Gucci Mane",
    age: calculateAge(1980, 2, 12),
    genre: ["Trap"],
    from: "Bessemer, Alabama",
    monthly: "10M+",
    debut: 2005,
  },
  {
    name: "Baby Keem",
    age: calculateAge(2000, 10, 22),
    genre: ["Rap"],
    from: "Las Vegas, Nevada",
    monthly: "15M+",
    debut: 2018,
  },
  {
    name: "Stormzy",
    age: calculateAge(1993, 7, 26),
    genre: ["Grime"],
    from: "London, England",
    monthly: "5M+",
    debut: 2014,
  },
  {
    name: "Skepta",
    age: calculateAge(1982, 9, 19),
    genre: ["Grime"],
    from: "Tottenham, London",
    monthly: "5M+",
    debut: 2006,
  },
  {
    name: "Nemzzz",
    age: calculateAge(2004, 3, 28),
    genre: ["Rap", "Trap"],
    from: "London, England",
    monthly: "5M+",
    debut: 2018,
  },
  {
    name: "Lil Peep",
    age: 21,
    genre: ["Emo Rap"],
    from: "Long Beach, California",
    monthly: "15M+",
    debut: 2015,
  },
  {
    name: "Frank Ocean",
    age: calculateAge(1987, 10, 28),
    genre: ["R&B"],
    from: "Long Beach, California",
    monthly: "35M+",
    debut: 2010,
  },
  {
    name: "Dave",
    age: calculateAge(1998, 6, 5),
    genre: ["Rap"],
    from: "Brixton, London",
    monthly: "15M+",
    debut: 2016,
  },
  {
    name: "Young Thug",
    age: calculateAge(1991, 8, 16),
    genre: ["Trap"],
    from: "Atlanta, Georgia",
    monthly: "25M+",
    debut: 2010,
  },
  {
    name: "Chief Keef",
    age: calculateAge(1995, 8, 15),
    genre: ["Trap", "Drill"],
    from: "Chicago, Illinois",
    monthly: "10M+",
    debut: 2011,
  },
  {
    name: "Trippie Redd",
    age: calculateAge(1999, 6, 18),
    genre: ["Emo Rap"],
    from: "Columbus, Ohio",
    monthly: "20M+",
    debut: 2014,
  },
];

export default rappers;
